/**
 * NumberCove renders all of its visuals with vector primitives — LinearGradient
 * backgrounds, react-native-svg (bubbles, path, waves) and lucide-react-native
 * icons. There are intentionally NO runtime raster (PNG) dependencies, so there
 * is nothing to `require()` here and no missing-asset build risk.
 *
 * The launcher icon (assets.json icon_1024) is generated by the pipeline and
 * wired straight into the Android mipmap folders, not imported by JS.
 */
export {};
